apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ing
  namespace: ingress-nginx
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/ingress-nginx/charts/ingress-nginx-4.8.1.tgz
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-config-02
        namespace: ingress-nginx
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
