apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ing
  namespace: app
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 5m
  chart:
    spec:
      chart: charts/ingrss-nginx
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-config-01
        namespace: app
